#!/usr/bin/env python
# -*- python -*-

import sys
import os

class Seal:
    def __init__(self, options):
        self.options = options

    def convert(self):
        pass

if __name__ == "__main__":
    from optparse import OptionParser
    #require 'src/about'
  
    options_dict = { "config": '\\openany' }
    parser = OptionParser(usage="seal-convert [options] source [destination]")
    # extra_pre = "seal (commit #{Seal::COMMIT}) from #{Seal::DATE}"
    # extra_post = """seal-convert is a command line tool to convert
    # the Dylanchords HTML files to LaTeX"""
    # version = "from commit #{Seal::COMMIT}"

    parser.add_option("-f", "--[no-]force", dest="force", default=False,
                      help="Overwrite existing directories")
    parser.add_option("-q", "--[no-]quiet", dest="quiet", default=False,
                       help="Don't write what is going on")
    parser.add_option("-o", "--options [list]", action="append", type="string",
                      help="Set a configuration option", dest="config")
    # Anyone of 'openright', 'openleft', 'openany'

    # "--copyright", "Show copyright (revised BSD License)"
    # Seal::LICENSE
    # exit

    (options, args) = parser.parse_args()

    if not args:
        parser.error("need path to source HTMLs")
        sys.exit(1)
    
    options_dict["source"] = args.pop(0)
    if args:
        options_dict["destination"] = args.pop(0)
    else:
        options_dict["destination"] = os.path.join(os.getcwd(), 'book')

    seal = Seal(options_dict)

    try:
        seal.convert
    except KeyboardInterrupt:
        sys.exit(2)
